version: "3"
services:
  players:
    build: ./players
    ports:
      - 5000:80
    volumes:
      - ./players/app:/app
  site:
    build: ./site
    ports:
      - 5001:80
    depends_on:
      - players
    volumes:
      - ./site:/src