version: "3"

networks:
  loki:
    external: true

services:

  #my-nginx-service:
  # image: nginx
  # container_name: nginx-service
  # ports:
  #   - 8000:80
  # environment:
  #   - FOO=bar
  # logging:
  #   driver: loki
  #   options:
  #     loki-url: http://localhost:3100/loki/api/v1/push
  #     loki-external-labels: job=dockerlogs,owner=maniuk,environment=development
  # networks:
  #   - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
        #volumes:
        #- "./loki/loki-config.yml:/etc/config/loki-config.yml"    
        #entrypoint:
        #- "/usr/bin/loki"
        #- "-config.file=/etc/config/loki-config.yml"
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: root
    ports:
      - "9080:9080"
    volumes:
      #- "./logs:/var/log/demo"
      #- "/var/log/system.log:/var/log/root/system.log"
      - "./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml"
        #entrypoint:
        #- "/usr/bin/promtail"
        #- "-config.file=/etc/config/promtail-local-config.yml"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
        #volumes:
        #- "./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    networks:
      - loki
    depends_on:
      - loki
