server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: demo
  static_configs:
  - targets:
      - localhost
    labels:
      job: demologs
      __path__: /var/log/demo/*log
- job_name: root
  static_configs:
  - targets:
      - localhost
    labels:
      job: rootlogs
      __path__: /var/log/root/*log
