version: '3'

services:

  nginx:
    image: nginx:latest
    hostname: cloud.thibgil.home
    container_name: nginx
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/cloud.thibgil.home.crt:/etc/nginx/ssl/certs/cloud.thibgil.home.crt
      - ./nginx/ssl/cloud.thibgil.home.key:/etc/nginx/ssl/private/cloud.thibgil.home.key
    ports:
      - 80:80
      - 443:443
    links:
      - nextcloud
      - nextcloud_db

  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
     - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD  
     - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE  
     - MYSQL_USER=$NEXTCLOUD_MYSQL_USER  
     - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
  
  nextcloud:
    image: nextcloud
    restart: always
    container_name: nextcloud
    hostname: nextcloud.docker
#    ports:
#      - 8080:80
    links:
      - nextcloud_db
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD

